### ISSUE TITLE
"Examples..." item from menu is not working

### ISSUE THREAD

**Issue by danielnaber** [languagetooler-gmbh/languagetool-website-2018#5]
Click on an error: most of them have an "Examples..." item. However, nothing happens. Maybe it's just the library which is missing.

**Comment by danielnaber** [comment]
Maybe this is the same issue: paste text with an error into the main textarea, select a correction -> `ReferenceError: vex is not defined` on console and thus the dialog that should popup doesn't appear.

**Comment by neprev** [comment]
@danielnaber you mean the popup that falls if you click on the word with an error? I added Vex library to the project - it works now. Btw this code (vex) is missing on production. Please check

**Comment by danielnaber** [comment]
Go to http://127.0.0.1:8000/de/, click and error and select "Examples..." form the menu (maybe your browser needs to be set to German for that). Nothing happens, the dialog doesn't appear. No error on console.

**Comment by danielnaber** [comment]
I see the problem is not in the frontend - I'll fix the backend part.

**Comment by danielnaber** [comment]
Fixed, only the close button of the dialog is messed up for some reason. Could you have a look at that?

**Comment by neprev** [comment]
@danielnaber I fixed the close button. Btw i didn't have the "examples" in menu because if this code in editir_plugin2.js
<img width="1073" alt="screen shot 2018-04-15 at 21 51 52" src="https://user-images.githubusercontent.com/28347933/38780414-8a7040a2-40f7-11e8-8770-9d0477de50e5.png">
Because for me address is localhost.
Please note that this feature will only work under certain conditions.
